### ISSUE TITLE
MultiDiGraph support

### ISSUE THREAD

**Issue by hpawa** [aplbrain/dotmotif#101]
Hey. Is it possible to add support for multidigraph?

**Comment by j6k4m8** [comment]
Hi @hpawa! This has been on my radar for a while, but I didn't have plans to implement it since I didn't have anyone looking for that particular use-case. Really glad you asked! 

I'm planning to add support for multigraphs to the GrandIsoExecutor this summer, and I'm curious if you could share more details about your use-case so I can be sure I meet your needs. 

As a short-term fix, the Neo4jExecutor is VERY close to supporting this, but it inserts a `DISTINCT` keyword into the query. If you are willing to play around a little bit with the queries that it generates (and you're alright with using the Neo4j executor), I can show you how to return multigraph results right away :)
