### ISSUE TITLE
Add docker-compose instructions

### ISSUE THREAD

**Issue by jtpdowns** [aplbrain/dotmotif#24]
If dotmotif were to be deployed in a Docker container, the default no-Neo4j-instance behavior would be to try to launch another container inside of the container. It would be good to describe the required steps to orchestrate an application container with a Neo4j container using docker-compose, which would allow you to network the two together and avoid the container-in-container problem.

**Comment by j6k4m8** [comment]
Big sigh of zero-github-issue relief: This is finally documented and explained in detail in [the wiki](https://github.com/aplbrain/dotmotif/wiki/Neo4j).

And, incidentally: The pain-threshold for using the Neo4j executor is now way higher, since the `GrandIsoExecutor` bites way into the range of graph-sizes for which it used to make sense to switch to a graph database.

Woo! 🎉
